spring:
  datasource:
    username: root
    url: jdbc:mysql://localhost:3306/student_local_db
    password: Root@123
  jpa:
    open-in-view: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
  config:
    activate:
      on-profile: dev
server:
  error:
    include-message: always

management:
  endpoints:
    web:
      exposure:
        include: "*"
---

spring:
  datasource:
    username: root
    url: jdbc:mysql://localhost:3306/student_local_db_qa
    password: Root@123
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
  config:
    activate:
      on-profile: qa
server:
  error:
    include-message: always

---

spring:
  datasource:
    username: root
    url: jdbc:mysql://localhost:3306/student_local_db_prod
    password: Root@123
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
  config:
    activate:
      on-profile: prod
server:
  error:
    include-message: always

---

spring:
  profiles:
    active: dev
